/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Local Web document and Current JD Task wire contract.
 */
export interface JobAnalysisWorkspaceContract {}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentMetadataWrite".
 */
export interface DocumentMetadataWrite {
  title: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentMetadataView".
 */
export interface DocumentMetadataView {
  document_id: string;
  title: string;
  updated_at: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentSummary".
 */
export interface DocumentSummary {
  document_id: string;
  title: string;
  task_count: number;
  updated_at: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdHeaderView".
 */
export interface JdHeaderView {
  competency_name: string | null;
  occupation_category_name: string | null;
  occupation_name: string | null;
  occupation_code: string | null;
  industry_name: string | null;
  industry_code: string | null;
  work_description: string | null;
  competency_level: number | null;
  notes: string | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdHeaderWrite".
 */
export interface JdHeaderWrite {
  competency_name: string | null;
  occupation_category_name: string | null;
  occupation_name: string | null;
  occupation_code: string | null;
  industry_name: string | null;
  industry_code: string | null;
  work_description: string | null;
  competency_level: number | null;
  notes: string | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ReadinessIssueView".
 */
export interface ReadinessIssueView {
  code:
    | "competency_name_missing"
    | "work_description_missing"
    | "competency_level_missing"
    | "task_duty_missing"
    | "task_competency_level_missing"
    | "duty_without_task";
  field: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentReadinessView".
 */
export interface DocumentReadinessView {
  issues: ReadinessIssueView[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "Enabler".
 */
export interface Enabler {
  kind: "tool_system" | "method" | "knowledge" | "skill" | "other";
  name: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdTaskWrite".
 */
export interface JdTaskWrite {
  statement: string;
  purpose_result: string | null;
  context: string | null;
  frequency_text: string | null;
  responsibility_role: "primary" | "shared" | "assist" | "" | null;
  enablers: Enabler[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdTaskView".
 */
export interface JdTaskView {
  task_id: string;
  statement: string;
  purpose_result: string | null;
  context: string | null;
  frequency_text: string | null;
  responsibility_role: "primary" | "shared" | "assist" | null;
  enablers: Enabler[];
  display_order: number;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "OpksItemWrite".
 */
export interface OpksItemWrite {
  entity_kind: "output" | "indicator" | "knowledge" | "skill" | "attitude";
  text: string;
  task_refs: string[];
  indicator_refs: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "OpksItemView".
 */
export interface OpksItemView {
  entity_id: string;
  entity_kind: "output" | "indicator" | "knowledge" | "skill" | "attitude";
  text: string;
  task_refs: string[];
  indicator_refs: string[];
  evidence_quotes: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "OpksGenerationView".
 */
export interface OpksGenerationView {
  outcome: "proposed" | "no_grounded_candidates";
  proposal_ids: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "OpksProposalView".
 */
export interface OpksProposalView {
  proposal_id: string;
  operation_id: string;
  entity_id: string;
  entity_kind: "output" | "indicator" | "knowledge" | "skill" | "attitude";
  action: "add" | "revise" | "remove";
  status: "pending" | "deferred" | "accepted" | "edited" | "rejected" | "stale";
  before: OpksItemView | null;
  after: OpksItemView | null;
  edited_after: OpksItemView | null;
  rejection_reason: string | null;
  stale_reason: string | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentView".
 */
export interface DocumentView {
  document_id: string;
  title: string;
  updated_at: string;
  jd_header: JdHeaderView;
  readiness: DocumentReadinessView;
  tasks: JdTaskView[];
  opks_items: OpksItemView[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ConversationTurnView".
 */
export interface ConversationTurnView {
  turn_id: string;
  speaker: "employee" | "consultant";
  text: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ActiveQuestionView".
 */
export interface ActiveQuestionView {
  turn_id: string;
  text: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProposalJdEntryView".
 */
export interface ProposalJdEntryView {
  task_id: string;
  value: JdTaskView | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProposalView".
 */
export interface ProposalView {
  proposal_id: string;
  action: "add" | "revise" | "withdraw" | "merge" | "split";
  status: "pending" | "deferred" | "accepted" | "edited" | "rejected" | "revision_requested" | "stale";
  jd_before: ProposalJdEntryView[];
  jd_after: ProposalJdEntryView[];
  edited_jd_after: ProposalJdEntryView[] | null;
  rejection_reason: string | null;
  stale_reason: string | null;
  evidence_quotes: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ConsultationView".
 */
export interface ConsultationView {
  document: DocumentMetadataView;
  conversation: ConversationTurnView[];
  active_question: ActiveQuestionView | null;
  proposals: ProposalView[];
  opks_proposals: OpksProposalView[];
  tasks: JdTaskView[];
  opks_items: OpksItemView[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "EmployeeTurnWrite".
 */
export interface EmployeeTurnWrite {
  text: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProposalDecisionWrite".
 */
export interface ProposalDecisionWrite {
  decision: "accepted" | "edited" | "rejected" | "deferred";
  edited_jd_after?: ProposalJdEntryView[] | null;
  reason?: string | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "OpksProposalDecisionWrite".
 */
export interface OpksProposalDecisionWrite {
  decision: "accepted" | "edited" | "rejected" | "deferred";
  edited_text?: string | null;
  reason?: string | null;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "TaskOrderWrite".
 */
export interface TaskOrderWrite {
  ordered_task_ids: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProblemFieldError".
 */
export interface ProblemFieldError {
  field: string;
  message: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProblemDetail".
 */
export interface ProblemDetail {
  type:
    | "https://caliburn.dev/problems/job-analysis/document-not-found"
    | "https://caliburn.dev/problems/job-analysis/task-not-found"
    | "https://caliburn.dev/problems/job-analysis/idempotency-conflict"
    | "https://caliburn.dev/problems/job-analysis/authority-conflict"
    | "https://caliburn.dev/problems/job-analysis/invalid-task-order"
    | "https://caliburn.dev/problems/job-analysis/invalid-request"
    | "https://caliburn.dev/problems/job-analysis/proposal-not-found"
    | "https://caliburn.dev/problems/job-analysis/consultant-unavailable"
    | "https://caliburn.dev/problems/job-analysis/opks-item-not-found";
  title: string;
  status: number;
  detail?: string | null;
  errors?: ProblemFieldError[] | null;
}
