/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Local Web document and Current JD Task wire contract.
 */
export interface JobAnalysisWorkspaceContract {}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentMetadataWrite".
 */
export interface DocumentMetadataWrite {
  title: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentMetadataView".
 */
export interface DocumentMetadataView {
  document_id: string;
  title: string;
  updated_at: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentSummary".
 */
export interface DocumentSummary {
  document_id: string;
  title: string;
  task_count: number;
  updated_at: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "Enabler".
 */
export interface Enabler {
  kind: "tool_system" | "method" | "knowledge" | "skill" | "other";
  name: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdTaskWrite".
 */
export interface JdTaskWrite {
  statement: string;
  purpose_result: string | null;
  context: string | null;
  frequency_text: string | null;
  responsibility_role: "primary" | "shared" | "assist" | "" | null;
  enablers: Enabler[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "JdTaskView".
 */
export interface JdTaskView {
  task_id: string;
  statement: string;
  purpose_result: string | null;
  context: string | null;
  frequency_text: string | null;
  responsibility_role: "primary" | "shared" | "assist" | null;
  enablers: Enabler[];
  display_order: number;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "DocumentView".
 */
export interface DocumentView {
  document_id: string;
  title: string;
  updated_at: string;
  tasks: JdTaskView[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "TaskOrderWrite".
 */
export interface TaskOrderWrite {
  ordered_task_ids: string[];
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProblemFieldError".
 */
export interface ProblemFieldError {
  field: string;
  message: string;
}
/**
 * This interface was referenced by `JobAnalysisWorkspaceContract`'s JSON-Schema
 * via the `definition` "ProblemDetail".
 */
export interface ProblemDetail {
  type:
    | "https://caliburn.dev/problems/job-analysis/document-not-found"
    | "https://caliburn.dev/problems/job-analysis/task-not-found"
    | "https://caliburn.dev/problems/job-analysis/idempotency-conflict"
    | "https://caliburn.dev/problems/job-analysis/authority-conflict"
    | "https://caliburn.dev/problems/job-analysis/invalid-task-order"
    | "https://caliburn.dev/problems/job-analysis/invalid-request";
  title: string;
  status: number;
  detail?: string | null;
  errors?: ProblemFieldError[] | null;
}
