"""Pure, immutable domain contracts for interview vNext."""

from .commands import (
    ApplyCandidateProposalsCommand,
    ApplyGapProposalsCommand,
    ApplyInferenceProposalsCommand,
    ApplyReviewDecisionCommand,
    ApplyTurnInterpretationCommand,
    AppendConsultantQuestionCommand,
    AppendEmployeeTurnCommand,
    DecideInferenceCommand,
    InvalidateQuestionFrameCommand,
    OpenEpisodeCommand,
    SupersedeInferenceCommand,
    TransitionCandidateCommand,
    TransitionEpisodeCommand,
    TransitionGapCommand,
    TransitionSessionCommand,
    WithdrawEvidenceCommand,
)
from .evidence import Evidence, EvidenceQualifiers, Inference
from .episode import EpisodeState, Gap
from .interpretation import TurnInterpretationRecord
from .job_model import CandidateJobItem
from .question_frame import QuestionFrame, QuestionFrameDefinition
from .reducers import (
    ReductionResult,
    append_consultant_question,
    append_employee_turn,
    apply_candidate_proposals,
    apply_gap_proposals,
    apply_inference_proposals,
    apply_review_decision,
    apply_turn_interpretation,
    decide_inference,
    invalidate_question_frame,
    open_episode,
    supersede_inference,
    transition_candidate,
    transition_episode,
    transition_gap,
    transition_session,
    withdraw_evidence,
)
from .review import ReviewDecision
from .session import InterviewSession
from .state import InterviewState
from .support import ContextualAnswerSupport, LiteralEmployeeSpanSupport, QuoteSpan
from .transcript import TranscriptTurn

__all__ = [
    "AppendConsultantQuestionCommand",
    "AppendEmployeeTurnCommand",
    "ApplyCandidateProposalsCommand",
    "ApplyGapProposalsCommand",
    "ApplyInferenceProposalsCommand",
    "ApplyReviewDecisionCommand",
    "ApplyTurnInterpretationCommand",
    "CandidateJobItem",
    "ContextualAnswerSupport",
    "EpisodeState",
    "Evidence",
    "EvidenceQualifiers",
    "Gap",
    "Inference",
    "InterviewSession",
    "InterviewState",
    "InvalidateQuestionFrameCommand",
    "LiteralEmployeeSpanSupport",
    "QuestionFrame",
    "QuestionFrameDefinition",
    "QuoteSpan",
    "ReductionResult",
    "ReviewDecision",
    "TranscriptTurn",
    "TransitionSessionCommand",
    "TurnInterpretationRecord",
    "DecideInferenceCommand",
    "OpenEpisodeCommand",
    "SupersedeInferenceCommand",
    "TransitionCandidateCommand",
    "TransitionEpisodeCommand",
    "TransitionGapCommand",
    "WithdrawEvidenceCommand",
    "append_consultant_question",
    "append_employee_turn",
    "apply_candidate_proposals",
    "apply_gap_proposals",
    "apply_inference_proposals",
    "apply_review_decision",
    "apply_turn_interpretation",
    "decide_inference",
    "invalidate_question_frame",
    "open_episode",
    "supersede_inference",
    "transition_candidate",
    "transition_episode",
    "transition_gap",
    "transition_session",
    "withdraw_evidence",
]
