"""Stable machine-readable domain rejection reasons."""

from enum import StrEnum


class ReasonCode(StrEnum):
    APPLIED = "applied"
    DUPLICATE_COMMAND = "duplicate_command"
    STATE_VERSION_CONFLICT = "state_version_conflict"
    COMMAND_TIME_REGRESSION = "command_time_regression"
    INVALID_SESSION_TRANSITION = "invalid_session_transition"
    TERMINAL_SESSION = "terminal_session"
    STOP_REASON_REQUIRED = "stop_reason_required"
    ACTIVE_EPISODE_MUST_CLOSE = "active_episode_must_close"
    SESSION_ID_MISMATCH = "session_id_mismatch"
    TURN_ID_DUPLICATE = "turn_id_duplicate"
    CLIENT_TURN_ID_DUPLICATE = "client_turn_id_duplicate"
    TURN_SEQUENCE_INVALID = "turn_sequence_invalid"
    PREVIOUS_TURN_MISMATCH = "previous_turn_mismatch"
    TURN_NOT_FOUND = "turn_not_found"
    EVIDENCE_ID_DUPLICATE = "evidence_id_duplicate"
    EVIDENCE_PROPOSAL_STATUS_INVALID = "evidence_proposal_status_invalid"
    EVIDENCE_TURN_MISMATCH = "evidence_turn_mismatch"
    EVIDENCE_EPISODE_INVALID = "evidence_episode_invalid"
    EVIDENCE_REQUIRES_EMPLOYEE_TURN = "evidence_requires_employee_turn"
    QUOTE_SPAN_OUT_OF_RANGE = "quote_span_out_of_range"
    QUOTE_MISMATCH = "quote_mismatch"
    NORMALIZATION_VERSION_INVALID = "normalization_version_invalid"
    SUPERSEDE_TARGET_NOT_FOUND = "supersede_target_not_found"
    SUPERSEDE_TARGET_NOT_ACTIVE = "supersede_target_not_active"
    SUPERSEDE_TARGET_DUPLICATE = "supersede_target_duplicate"
    EVIDENCE_NOT_FOUND = "evidence_not_found"
    EVIDENCE_NOT_ACTIVE = "evidence_not_active"
    EVIDENCE_WITHDRAW_TURN_INVALID = "evidence_withdraw_turn_invalid"
    EPISODE_NOT_FOUND = "episode_not_found"
    EPISODE_ID_DUPLICATE = "episode_id_duplicate"
    ACTIVE_EPISODE_EXISTS = "active_episode_exists"
    EPISODE_OPEN_TURN_INVALID = "episode_open_turn_invalid"
    EPISODE_TRANSITION_INVALID = "episode_transition_invalid"
    EPISODE_HAS_UNRESOLVED_GAPS = "episode_has_unresolved_gaps"
    GAP_ID_DUPLICATE = "gap_id_duplicate"
    GAP_PROPOSAL_INVALID = "gap_proposal_invalid"
    GAP_NOT_FOUND = "gap_not_found"
    GAP_TRANSITION_INVALID = "gap_transition_invalid"
    GAP_TURN_INVALID = "gap_turn_invalid"
    INFERENCE_ID_DUPLICATE = "inference_id_duplicate"
    INFERENCE_PROPOSAL_INVALID = "inference_proposal_invalid"
    INFERENCE_EVIDENCE_NOT_FOUND = "inference_evidence_not_found"
    INFERENCE_NOT_FOUND = "inference_not_found"
    INFERENCE_DECISION_INVALID = "inference_decision_invalid"
    CANDIDATE_ID_DUPLICATE = "candidate_id_duplicate"
    CANDIDATE_PROPOSAL_INVALID = "candidate_proposal_invalid"
    CANDIDATE_NOT_FOUND = "candidate_not_found"
    CANDIDATE_TRANSITION_INVALID = "candidate_transition_invalid"
    CANDIDATE_INFERENCE_NOT_FOUND = "candidate_inference_not_found"
    REVIEW_ID_DUPLICATE = "review_id_duplicate"
    REVIEW_DECISION_INVALID = "review_decision_invalid"
    REVIEW_CANDIDATE_NOT_REVIEWABLE = "review_candidate_not_reviewable"
    REFERENCE_ONLY_CANDIDATE = "reference_only_candidate"
    CANDIDATE_EVIDENCE_INACTIVE = "candidate_evidence_inactive"
    CANDIDATE_CURRENT_SCOPE_INVALID = "candidate_current_scope_invalid"
    ABILITY_CROSS_EPISODE_EVIDENCE_REQUIRED = "ability_cross_episode_evidence_required"
    NUMERIC_THRESHOLD_SOURCE_REQUIRED = "numeric_threshold_source_required"
    HUMAN_DECISION_PROTECTED = "human_decision_protected"
    # R5 appends at the tail: enum order is a public deterministic order and
    # existing values are never renamed (amendment plan §7.7).
    QUESTION_FRAME_DEFINITION_INVALID = "question_frame_definition_invalid"
    QUESTION_FRAME_ANSWER_PENDING = "question_frame_answer_pending"
    QUESTION_FRAME_NOT_ACTIVE = "question_frame_not_active"
    QUESTION_FRAME_NOT_IMMEDIATE = "question_frame_not_immediate"
    QUESTION_FRAME_SCOPE_MISMATCH = "question_frame_scope_mismatch"
    QUESTION_FRAME_HASH_MISMATCH = "question_frame_hash_mismatch"
    QUESTION_FRAME_TARGET_INVALID = "question_frame_target_invalid"
    QUESTION_FRAME_NOT_FOUND = "question_frame_not_found"
    TURN_ALREADY_INTERPRETED = "turn_already_interpreted"
    TURN_INTERPRETATION_PENDING = "turn_interpretation_pending"
    INTERPRETATION_SCOPE_MISMATCH = "interpretation_scope_mismatch"
    INTERPRETATION_EVIDENCE_MISMATCH = "interpretation_evidence_mismatch"
    INTERPRETATION_ID_DUPLICATE = "interpretation_id_duplicate"
    CONTEXTUAL_SUPPORT_MISMATCH = "contextual_support_mismatch"
    UNSUPPORTED_PERSISTED_SCHEMA_VERSION = "unsupported_persisted_schema_version"
