"""Stable machine-readable domain rejection reasons."""

from enum import StrEnum


class ReasonCode(StrEnum):
    APPLIED = "applied"
    DUPLICATE_COMMAND = "duplicate_command"
    STATE_VERSION_CONFLICT = "state_version_conflict"
    COMMAND_TIME_REGRESSION = "command_time_regression"
    INVALID_SESSION_TRANSITION = "invalid_session_transition"
    TERMINAL_SESSION = "terminal_session"
    STOP_REASON_REQUIRED = "stop_reason_required"
    ACTIVE_EPISODE_MUST_CLOSE = "active_episode_must_close"
    SESSION_ID_MISMATCH = "session_id_mismatch"
    TURN_ID_DUPLICATE = "turn_id_duplicate"
    CLIENT_TURN_ID_DUPLICATE = "client_turn_id_duplicate"
    TURN_SEQUENCE_INVALID = "turn_sequence_invalid"
    PREVIOUS_TURN_MISMATCH = "previous_turn_mismatch"
    TURN_NOT_FOUND = "turn_not_found"
    EVIDENCE_ID_DUPLICATE = "evidence_id_duplicate"
    EVIDENCE_PROPOSAL_STATUS_INVALID = "evidence_proposal_status_invalid"
    EVIDENCE_TURN_MISMATCH = "evidence_turn_mismatch"
    EVIDENCE_REQUIRES_EMPLOYEE_TURN = "evidence_requires_employee_turn"
    QUOTE_SPAN_OUT_OF_RANGE = "quote_span_out_of_range"
    QUOTE_MISMATCH = "quote_mismatch"
    NORMALIZATION_VERSION_INVALID = "normalization_version_invalid"
    SUPERSEDE_TARGET_NOT_FOUND = "supersede_target_not_found"
    SUPERSEDE_TARGET_NOT_ACTIVE = "supersede_target_not_active"
    SUPERSEDE_TARGET_DUPLICATE = "supersede_target_duplicate"
    EPISODE_NOT_FOUND = "episode_not_found"
    REFERENCE_ONLY_CANDIDATE = "reference_only_candidate"
    CANDIDATE_EVIDENCE_INACTIVE = "candidate_evidence_inactive"
    CANDIDATE_CURRENT_SCOPE_INVALID = "candidate_current_scope_invalid"
    ABILITY_CROSS_EPISODE_EVIDENCE_REQUIRED = "ability_cross_episode_evidence_required"
    NUMERIC_THRESHOLD_SOURCE_REQUIRED = "numeric_threshold_source_required"
    HUMAN_DECISION_PROTECTED = "human_decision_protected"
