# generated by datamodel-codegen:
#   filename:  job-analysis-workspace.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class JobAnalysisWorkspaceContract(BaseModel):
    """
    Local Web document and Current JD Task wire contract.
    """

    model_config = ConfigDict(
        extra='forbid',
    )


class DocumentMetadataWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str


class DocumentMetadataView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    updated_at: AwareDatetime


class DocumentSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    task_count: conint(ge=0)
    updated_at: AwareDatetime


class Kind(StrEnum):
    tool_system = 'tool_system'
    method = 'method'
    knowledge = 'knowledge'
    skill = 'skill'
    other = 'other'


class Enabler(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    name: str


class ResponsibilityRole(Enum):
    primary = 'primary'
    shared = 'shared'
    assist = 'assist'
    field_ = ''
    NoneType_None = None


class JdTaskWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    statement: str
    purpose_result: str | None
    context: str | None
    frequency_text: str | None
    responsibility_role: ResponsibilityRole | None
    enablers: list[Enabler]


class ResponsibilityRole1(Enum):
    primary = 'primary'
    shared = 'shared'
    assist = 'assist'
    NoneType_None = None


class JdTaskView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    statement: str
    purpose_result: str | None
    context: str | None
    frequency_text: str | None
    responsibility_role: ResponsibilityRole1 | None
    enablers: list[Enabler]
    display_order: conint(ge=0)


class DocumentView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    updated_at: AwareDatetime
    tasks: list[JdTaskView]


class TaskOrderWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ordered_task_ids: list[str]


class ProblemFieldError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    message: str


class Type(StrEnum):
    https___caliburn_dev_problems_job_analysis_document_not_found = (
        'https://caliburn.dev/problems/job-analysis/document-not-found'
    )
    https___caliburn_dev_problems_job_analysis_task_not_found = (
        'https://caliburn.dev/problems/job-analysis/task-not-found'
    )
    https___caliburn_dev_problems_job_analysis_idempotency_conflict = (
        'https://caliburn.dev/problems/job-analysis/idempotency-conflict'
    )
    https___caliburn_dev_problems_job_analysis_authority_conflict = (
        'https://caliburn.dev/problems/job-analysis/authority-conflict'
    )
    https___caliburn_dev_problems_job_analysis_invalid_task_order = (
        'https://caliburn.dev/problems/job-analysis/invalid-task-order'
    )
    https___caliburn_dev_problems_job_analysis_invalid_request = (
        'https://caliburn.dev/problems/job-analysis/invalid-request'
    )


class ProblemDetail(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Type
    title: str
    status: conint(ge=400, le=599)
    detail: str | None = None
    errors: list[ProblemFieldError] | None = None
