# generated by datamodel-codegen:
#   filename:  job-analysis-workspace.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class JobAnalysisWorkspaceContract(BaseModel):
    """
    Local Web document and Current JD Task wire contract.
    """

    model_config = ConfigDict(
        extra='forbid',
    )


class DocumentMetadataWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str


class DocumentMetadataView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    updated_at: AwareDatetime


class DocumentSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    task_count: conint(ge=0)
    updated_at: AwareDatetime


class JdHeaderView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    competency_name: str | None
    occupation_category_name: str | None
    occupation_name: str | None
    occupation_code: str | None
    industry_name: str | None
    industry_code: str | None
    work_description: str | None
    competency_level: conint(ge=1, le=6) | None
    notes: str | None


class JdHeaderWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    competency_name: str | None
    occupation_category_name: str | None
    occupation_name: str | None
    occupation_code: str | None
    industry_name: str | None
    industry_code: str | None
    work_description: str | None
    competency_level: conint(ge=1, le=6) | None
    notes: str | None


class Code(StrEnum):
    competency_name_missing = 'competency_name_missing'
    work_description_missing = 'work_description_missing'
    competency_level_missing = 'competency_level_missing'
    task_duty_missing = 'task_duty_missing'
    task_competency_level_missing = 'task_competency_level_missing'
    duty_without_task = 'duty_without_task'


class ReadinessIssueView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    field: str


class DocumentReadinessView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issues: list[ReadinessIssueView]


class Kind(StrEnum):
    tool_system = 'tool_system'
    method = 'method'
    knowledge = 'knowledge'
    skill = 'skill'
    other = 'other'


class Enabler(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    name: str


class DutyWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    statement: str


class DutyView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duty_id: str
    statement: str
    display_order: conint(ge=0)


class ResponsibilityRole(Enum):
    primary = 'primary'
    shared = 'shared'
    assist = 'assist'
    field_ = ''
    NoneType_None = None


class JdTaskWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    statement: str
    purpose_result: str | None
    context: str | None
    frequency_text: str | None
    responsibility_role: ResponsibilityRole | None
    enablers: list[Enabler]
    duty_id: str | None
    competency_level: conint(ge=1, le=6) | None


class ResponsibilityRole1(Enum):
    primary = 'primary'
    shared = 'shared'
    assist = 'assist'
    NoneType_None = None


class JdTaskView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    statement: str
    purpose_result: str | None
    context: str | None
    frequency_text: str | None
    responsibility_role: ResponsibilityRole1 | None
    enablers: list[Enabler]
    display_order: conint(ge=0)
    duty_id: str | None
    competency_level: conint(ge=1, le=6) | None


class EntityKind(StrEnum):
    output = 'output'
    indicator = 'indicator'
    knowledge = 'knowledge'
    skill = 'skill'
    attitude = 'attitude'


class OpksItemWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_kind: EntityKind
    text: str
    task_refs: list[str]
    indicator_refs: list[str]


class OpksItemView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_id: str
    entity_kind: EntityKind
    text: str
    task_refs: list[str]
    indicator_refs: list[str]
    evidence_quotes: list[str]
    display_order: conint(ge=0)


class Outcome(StrEnum):
    proposed = 'proposed'
    no_grounded_candidates = 'no_grounded_candidates'


class OpksGenerationView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outcome: Outcome
    proposal_ids: list[str]


class Action(StrEnum):
    add = 'add'
    revise = 'revise'
    remove = 'remove'


class Status(StrEnum):
    pending = 'pending'
    deferred = 'deferred'
    accepted = 'accepted'
    edited = 'edited'
    rejected = 'rejected'
    stale = 'stale'


class OpksProposalView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposal_id: str
    operation_id: str
    entity_id: str
    entity_kind: EntityKind
    action: Action
    status: Status
    before: OpksItemView | None
    after: OpksItemView | None
    edited_after: OpksItemView | None
    rejection_reason: str | None
    stale_reason: str | None


class DocumentView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: UUID
    title: str
    updated_at: AwareDatetime
    jd_header: JdHeaderView
    readiness: DocumentReadinessView
    duties: list[DutyView]
    tasks: list[JdTaskView]
    opks_items: list[OpksItemView]


class Speaker(StrEnum):
    employee = 'employee'
    consultant = 'consultant'


class ConversationTurnView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    turn_id: str
    speaker: Speaker
    text: str


class ActiveQuestionView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    turn_id: str
    text: str


class ProposalJdEntryView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    value: JdTaskView | None


class Action1(StrEnum):
    add = 'add'
    revise = 'revise'
    withdraw = 'withdraw'
    merge = 'merge'
    split = 'split'


class Status1(StrEnum):
    pending = 'pending'
    deferred = 'deferred'
    accepted = 'accepted'
    edited = 'edited'
    rejected = 'rejected'
    revision_requested = 'revision_requested'
    stale = 'stale'


class ProposalView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposal_id: str
    action: Action1
    status: Status1
    jd_before: list[ProposalJdEntryView]
    jd_after: list[ProposalJdEntryView]
    edited_jd_after: list[ProposalJdEntryView] | None
    rejection_reason: str | None
    stale_reason: str | None
    evidence_quotes: list[str]


class ConsultationView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document: DocumentMetadataView
    conversation: list[ConversationTurnView]
    active_question: ActiveQuestionView | None
    proposals: list[ProposalView]
    opks_proposals: list[OpksProposalView]
    duties: list[DutyView]
    tasks: list[JdTaskView]
    opks_items: list[OpksItemView]


class EmployeeTurnWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1)


class Decision(StrEnum):
    accepted = 'accepted'
    edited = 'edited'
    rejected = 'rejected'
    deferred = 'deferred'


class ProposalDecisionWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision: Decision
    edited_jd_after: list[ProposalJdEntryView] | None = None
    reason: str | None = None


class OpksProposalDecisionWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decision: Decision
    edited_text: str | None = None
    reason: str | None = None


class TaskOrderWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ordered_task_ids: list[str]


class DutyOrderWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ordered_duty_ids: list[str]


class OpksOrderWrite(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entity_kind: EntityKind
    ordered_entity_ids: list[str]


class ProblemFieldError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    message: str


class Type(StrEnum):
    https___caliburn_dev_problems_job_analysis_document_not_found = (
        'https://caliburn.dev/problems/job-analysis/document-not-found'
    )
    https___caliburn_dev_problems_job_analysis_task_not_found = (
        'https://caliburn.dev/problems/job-analysis/task-not-found'
    )
    https___caliburn_dev_problems_job_analysis_duty_not_found = (
        'https://caliburn.dev/problems/job-analysis/duty-not-found'
    )
    https___caliburn_dev_problems_job_analysis_idempotency_conflict = (
        'https://caliburn.dev/problems/job-analysis/idempotency-conflict'
    )
    https___caliburn_dev_problems_job_analysis_authority_conflict = (
        'https://caliburn.dev/problems/job-analysis/authority-conflict'
    )
    https___caliburn_dev_problems_job_analysis_invalid_task_order = (
        'https://caliburn.dev/problems/job-analysis/invalid-task-order'
    )
    https___caliburn_dev_problems_job_analysis_invalid_duty_order = (
        'https://caliburn.dev/problems/job-analysis/invalid-duty-order'
    )
    https___caliburn_dev_problems_job_analysis_invalid_opks_order = (
        'https://caliburn.dev/problems/job-analysis/invalid-opks-order'
    )
    https___caliburn_dev_problems_job_analysis_invalid_request = (
        'https://caliburn.dev/problems/job-analysis/invalid-request'
    )
    https___caliburn_dev_problems_job_analysis_proposal_not_found = (
        'https://caliburn.dev/problems/job-analysis/proposal-not-found'
    )
    https___caliburn_dev_problems_job_analysis_consultant_unavailable = (
        'https://caliburn.dev/problems/job-analysis/consultant-unavailable'
    )
    https___caliburn_dev_problems_job_analysis_opks_item_not_found = (
        'https://caliburn.dev/problems/job-analysis/opks-item-not-found'
    )


class ProblemDetail(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Type
    title: str
    status: conint(ge=400, le=599)
    detail: str | None = None
    errors: list[ProblemFieldError] | None = None
