erDiagram
    direction LR
    JD修訂 ||--o{ 任務選用 : 選定
    JD修訂 ||--o{ 能力選用 : 選定
    任務選用 ||--o{ 任務能力關係 : 使用
    能力選用 ||--o{ 任務能力關係 : 被使用
    JD修訂 {
        uuid 職務檔案身分
        uuid JD修訂身分
    }
    任務選用 {
        uuid 任務身分
        uuid 固定內容修訂
    }
    能力選用 {
        uuid 能力身分
        uuid 固定內容修訂
    }
    任務能力關係 {
        uuid 任務身分
        uuid 能力身分
    }
