"""Task 分析的兩份契約(§12)。

`result.py` 是 verifier 與下游吃的**內部**形狀;`wire.py` 的
`task_analysis_result.v2` 才是**送給模型**的形狀,兩者以
`wire_to_task_analysis_result()` 相接。
"""

from app.core.portable_schema import (
    ProviderSchemaPortabilityError,
    assert_portable_strict_output_schema,
    compact_strict_output_schema,
    expand_refs,
    schema_complexity,
)

from .prompt import TASK_ANALYSIS_INSTRUCTIONS
from .opks_result import (
    OpksDecision,
    OpksGenerationEntityKind,
    OpksResult,
    OpksResultItem,
)
from .opks_prompt import OPKS_INSTRUCTIONS
from .opks_wire import (
    OPKS_RESULT_WIRE_SCHEMA_NAME,
    OPKS_WIRE_SCHEMA_PATH,
    OpksResultWire,
    OpksWireItem,
    committed_opks_wire_schema,
    opks_result_wire_provider_schema,
    opks_wire_to_result,
    render_opks_wire_schema_file,
)
from .result import (
    TASK_ANALYSIS_RESULT_SCHEMA_NAME,
    ExcludePayload,
    IdentityAssessment,
    IdentityRelation,
    IssueResolution,
    IssueResolutionKind,
    NextQuestion,
    NextQuestionTarget,
    NextQuestionTargetKind,
    OpenIssuePayload,
    SignalAnchor,
    SignalDisposition,
    SplitChildPayload,
    SupportOrdinalRef,
    TaskAnalysisResult,
    TaskChangeKind,
    TaskChangePayload,
    WorkSignal,
)
from .wire import (
    NEUTRAL,
    WireMappingError,
    TASK_ANALYSIS_WIRE_SCHEMA_NAME,
    WIRE_SCHEMA_PATH,
    TaskAnalysisWire,
    WireAnchor,
    WireEnabler,
    WireIssueResolution,
    WireNextQuestion,
    WireNextQuestionTargetKind,
    WireRejectionCode,
    WireSignal,
    WireSplitChild,
    WireSupersession,
    WireTaskChange,
    WireTaskFields,
    WireWithdrawReason,
    committed_wire_schema,
    render_wire_schema_file,
    task_analysis_wire_provider_schema,
    wire_to_task_analysis_result,
)

__all__ = [
    "NEUTRAL",
    "OPKS_RESULT_WIRE_SCHEMA_NAME",
    "OPKS_INSTRUCTIONS",
    "OPKS_WIRE_SCHEMA_PATH",
    "OpksDecision",
    "OpksGenerationEntityKind",
    "OpksResult",
    "OpksResultItem",
    "OpksResultWire",
    "OpksWireItem",
    "TASK_ANALYSIS_INSTRUCTIONS",
    "TASK_ANALYSIS_RESULT_SCHEMA_NAME",
    "TASK_ANALYSIS_WIRE_SCHEMA_NAME",
    "WIRE_SCHEMA_PATH",
    "ExcludePayload",
    "IdentityAssessment",
    "IdentityRelation",
    "IssueResolution",
    "IssueResolutionKind",
    "NextQuestion",
    "NextQuestionTarget",
    "NextQuestionTargetKind",
    "OpenIssuePayload",
    "ProviderSchemaPortabilityError",
    "SignalAnchor",
    "SignalDisposition",
    "SplitChildPayload",
    "SupportOrdinalRef",
    "TaskAnalysisResult",
    "TaskAnalysisWire",
    "TaskChangeKind",
    "TaskChangePayload",
    "WireAnchor",
    "WireEnabler",
    "WireIssueResolution",
    "WireMappingError",
    "WireNextQuestion",
    "WireNextQuestionTargetKind",
    "WireRejectionCode",
    "WireSignal",
    "WireSplitChild",
    "WireSupersession",
    "WireTaskChange",
    "WireTaskFields",
    "WireWithdrawReason",
    "WorkSignal",
    "assert_portable_strict_output_schema",
    "committed_opks_wire_schema",
    "committed_wire_schema",
    "compact_strict_output_schema",
    "expand_refs",
    "opks_result_wire_provider_schema",
    "opks_wire_to_result",
    "render_wire_schema_file",
    "render_opks_wire_schema_file",
    "schema_complexity",
    "task_analysis_wire_provider_schema",
    "wire_to_task_analysis_result",
]
