# generated by datamodel-codegen:
#   filename:  ocs-document.schema.json
#   timestamp: 2026-06-27T19:02:14+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class CodeName(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str
    name: str


class CodeText(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str
    text: str


class VersionEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    version: str | None = None
    ocs_code: str | None = None
    ocs_name: str | None = None
    status: str | None = None
    update_note: str | None = None
    update_date: str | None = None


class VersionInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    versions: list[VersionEntry] | None = None


class OcsName(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    job_category_name: str | None = None
    occupation_name: str | None = None


class Category(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    job_categories: list[CodeName] | None = None
    occupations: list[CodeName] | None = None
    industries: list[CodeName] | None = None


class OcsProfile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocs_code: str
    ocs_name: OcsName | None = None
    category: Category | None = None
    job_description: str | None = None
    ocs_level: conint(ge=1, le=5) | None = None


class CompetencyBlock(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    competency_level: conint(ge=1, le=5) | None = None
    indicators: list[CodeText] | None = None
    outputs: list[CodeName] | None = None
    knowledge: list[CodeName] | None = None
    skills: list[CodeName] | None = None


class TaskGroup(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    task_codes: list[CodeName] | None = None
    competency_blocks: list[CompetencyBlock] | None = None


class OcuUnit(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocu_code: str | None = None
    ocu_name: str | None = None
    tasks: list[TaskGroup] | None = None


class OcsContent(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocu_units: list[OcuUnit] | None = None


class OcsAttitude(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    attitudes: list[CodeName] | None = None


class Notes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    prerequisites: list[str] | None = None
    supplements: list[str] | None = None


class OCSDocument(BaseModel):
    """
    職能基準(OCS)來源文件 — pdf-to-json 產出、ocs-indexer 消費的交換格式。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    version_info: VersionInfo | None = None
    ocs_profile: OcsProfile
    ocs_content: OcsContent | None = None
    ocs_attitude: OcsAttitude | None = None
    notes: Notes | None = None
