# generated by datamodel-codegen:
#   filename:  ocs-document.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint


class Quote(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    turn_id: int
    text: str


class PendingSrc(BaseModel):
    """
    修訂出處:ref_urn(官方來源)與 quote(訪談原話)可並存;「至少一」由 verify 層強制(ADR 0030)。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    ref_urn: str | None = None
    quote: Quote | None = None


class Op(Enum):
    add = 'add'
    mod = 'mod'
    del_ = 'del'


class PendingMark(BaseModel):
    """
    追蹤修訂標記(ADR 0030):AI 寫入一律以 pending 落文件,✓=去標、✗=還原;匯出/定稿由 _strip_underscore 剝除。mod 必帶 prev(舊值)。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    op: Op
    by: Literal['ai']
    turn_id: int
    prev: Any | None = None
    src: PendingSrc | None = None


class CodeName(BaseModel):
    """
    OCS code↔name 條目;code/name 容忍缺漏(消費端 lockstep 過濾),但結構必為物件(防 string 飄移)。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    code: str | None = None
    name: str | None = None
    field_pending: PendingMark | None = Field(None, alias='_pending')


class CodeText(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str | None = None
    text: str | None = None
    field_pending: PendingMark | None = Field(None, alias='_pending')


class VersionEntry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    version: str | None = None
    ocs_code: str | None = None
    ocs_name: str | None = None
    status: str | None = None
    update_note: str | None = None
    update_date: str | None = None


class VersionInfo(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    versions: list[VersionEntry] | None = Field([], validate_default=True)


class OcsName(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    job_category_name: str | None = None
    occupation_name: str | None = None


class Category(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    job_categories: list[CodeName] | None = Field([], validate_default=True)
    occupations: list[CodeName] | None = Field([], validate_default=True)
    industries: list[CodeName] | None = Field([], validate_default=True)


class FieldPending(BaseModel):
    """
    表頭 scalar 欄位的修訂標記集合(槽名→PendingMark;ADR 0030)。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    ocs_code: PendingMark | None = None
    job_description: PendingMark | None = None
    ocs_level: PendingMark | None = None


class OcsProfile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocs_code: str
    ocs_name: OcsName | None = Field({}, validate_default=True)
    category: Category | None = Field({}, validate_default=True)
    job_description: str | None = None
    ocs_level: conint(ge=1, le=5) | None = None
    field_pending: FieldPending | None = Field(
        None,
        alias='_pending',
        description='表頭 scalar 欄位的修訂標記集合(槽名→PendingMark;ADR 0030)。',
    )


class CompetencyBlock(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    competency_level: conint(ge=1, le=5) | None = None
    indicators: list[CodeText] | None = Field([], validate_default=True)
    outputs: list[CodeName] | None = Field([], validate_default=True)
    knowledge: list[CodeName] | None = Field([], validate_default=True)
    skills: list[CodeName] | None = Field([], validate_default=True)


class FieldPending1(BaseModel):
    """
    細項 scalar 槽的修訂標記集合(槽名→PendingMark;ADR 0030)。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    frequency: PendingMark | None = None
    time_share_pct: PendingMark | None = None
    duration: PendingMark | None = None
    volume: PendingMark | None = None
    trigger: PendingMark | None = None
    inputs: PendingMark | None = None
    tools: PendingMark | None = None
    collaborators: PendingMark | None = None
    wait_points: PendingMark | None = None
    exceptions: PendingMark | None = None
    standards: PendingMark | None = None


class TaskDetails(BaseModel):
    """
    任務客製細項(訪談引擎 v1,ADR 0023/spec 2026-07-05;OCS 官方來源沒有——由訪談產生,全部 optional。v3 起(ADR 0030)溯源住各槽 _pending.src;已確認值不帶溯源。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    frequency: str | None = None
    time_share_pct: confloat(ge=0.0, le=100.0) | None = None
    duration: str | None = None
    volume: str | None = None
    trigger: str | None = None
    inputs: str | None = None
    tools: str | None = None
    collaborators: str | None = None
    wait_points: str | None = None
    exceptions: str | None = None
    standards: str | None = None
    field_pending: FieldPending1 | None = Field(
        None,
        alias='_pending',
        description='細項 scalar 槽的修訂標記集合(槽名→PendingMark;ADR 0030)。',
    )


class TaskGroup(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    task_codes: list[CodeName] | None = Field([], validate_default=True)
    competency_blocks: list[CompetencyBlock] | None = Field([], validate_default=True)
    details: TaskDetails | None = None
    field_pending: PendingMark | None = Field(None, alias='_pending')


class OcuUnit(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocu_code: str | None = None
    ocu_name: str | None = None
    tasks: list[TaskGroup] | None = Field([], validate_default=True)
    field_pending: PendingMark | None = Field(None, alias='_pending')


class OcsContent(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ocu_units: list[OcuUnit] | None = Field([], validate_default=True)


class OcsAttitude(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    attitudes: list[CodeName] | None = Field([], validate_default=True)


class Notes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    prerequisites: list[str] | None = []
    supplements: list[str] | None = []


class OCSDocument(BaseModel):
    """
    職能基準(OCS)來源文件 — pdf-to-json 產出、ocs-indexer 消費的交換格式。
    """

    model_config = ConfigDict(
        extra='allow',
    )
    version_info: VersionInfo | None = Field({}, validate_default=True)
    ocs_profile: OcsProfile
    ocs_content: OcsContent | None = Field({}, validate_default=True)
    ocs_attitude: OcsAttitude | None = Field({}, validate_default=True)
    notes: Notes | None = Field({}, validate_default=True)
