"""Pure immutable Task（§9/§10）與 OPKS（ADR 0048–0051）contracts。"""

from .base import DomainModel, Identifier, NonEmptyText, TaskId
from .duty import Duty, DutyId
from .jd_header import JdHeader
from .opks import (
    CurrentJdOpks,
    OpksEntityKind,
    OpksEvidenceLink,
    OpksItem,
)
from .opks_proposal import (
    OPKS_ALLOWED_STATUS_TRANSITIONS,
    OPKS_TERMINAL_STATUSES,
    OpksProposal,
    OpksProposalAction,
    OpksProposalStatus,
    is_allowed_opks_transition,
)
from .proposal import (
    ALLOWED_STATUS_TRANSITIONS,
    TERMINAL_STATUSES,
    JdEntry,
    JdTask,
    JdTaskFields,
    MergeTarget,
    Proposal,
    ProposalAction,
    ProposalStatus,
    ProposalTarget,
    ResponsibilityRole,
    RevisionRequestResolution,
    SingleTaskTarget,
    SplitTarget,
    StagedTask,
    StagedTaskLineage,
    StagedWorkModelDelta,
    is_allowed_transition,
    jd_map,
    validate_edited_jd_after,
    withdraw_delta_matches_target_state,
)
from .sources import SourceAnchor, SourceKind, SourceRef, SupportLink
from .task import (
    Enabler,
    EnablerKind,
    Retirement,
    RetirementKind,
    RetirementReason,
    Task,
    TaskFields,
    TaskState,
)
from .work_model import (
    CurrentWorkModel,
    ExcludedSignal,
    ExclusionReason,
    OpenIssue,
    OpenIssueKind,
    OpenIssueTerminalResolution,
    OpenIssueTerminalResolutionKind,
    OpksGapAxis,
)

__all__ = [
    "ALLOWED_STATUS_TRANSITIONS",
    "OPKS_ALLOWED_STATUS_TRANSITIONS",
    "OPKS_TERMINAL_STATUSES",
    "CurrentJdOpks",
    "CurrentWorkModel",
    "DomainModel",
    "Duty",
    "DutyId",
    "Enabler",
    "EnablerKind",
    "ExcludedSignal",
    "ExclusionReason",
    "Identifier",
    "JdEntry",
    "JdHeader",
    "JdTask",
    "JdTaskFields",
    "MergeTarget",
    "NonEmptyText",
    "OpenIssue",
    "OpenIssueKind",
    "OpenIssueTerminalResolution",
    "OpenIssueTerminalResolutionKind",
    "OpksEntityKind",
    "OpksGapAxis",
    "OpksEvidenceLink",
    "OpksItem",
    "OpksProposal",
    "OpksProposalAction",
    "OpksProposalStatus",
    "Proposal",
    "ProposalAction",
    "ProposalStatus",
    "ProposalTarget",
    "Retirement",
    "RetirementKind",
    "RetirementReason",
    "ResponsibilityRole",
    "RevisionRequestResolution",
    "SingleTaskTarget",
    "SourceAnchor",
    "SourceKind",
    "SourceRef",
    "SplitTarget",
    "StagedTask",
    "StagedTaskLineage",
    "StagedWorkModelDelta",
    "SupportLink",
    "TERMINAL_STATUSES",
    "Task",
    "TaskFields",
    "TaskId",
    "TaskState",
    "is_allowed_transition",
    "is_allowed_opks_transition",
    "jd_map",
    "validate_edited_jd_after",
    "withdraw_delta_matches_target_state",
]
