"""Provider adapters:目前只有 OpenRouter,而且刻意不做 registry(T5)。"""

from .openrouter import (
    CHAT_COMPLETIONS_URL,
    ChatTransport,
    OpenRouterAdapter,
    OpenRouterConfig,
    ProviderFailure,
    ProviderFailureKind,
    ProviderOutcome,
    ProviderRefusal,
    ProviderText,
    TransportResponse,
    httpx_chat_transport,
)
from .openrouter_evidence import (
    LIMITATION_COST_UNUSABLE,
    LIMITATION_METADATA_MISSING,
    LIMITATION_REQUESTED_MISMATCH,
    LIMITATION_RESPONSE_MODEL_MISMATCH,
    LIMITATION_ROUTER_RETRIED,
    LIMITATION_SELECTED_MODEL_MISMATCH,
    LIMITATION_SELECTED_NOT_UNIQUE,
    LIMITATION_SELECTED_PROVIDER_MISMATCH,
    LIMITATION_STRATEGY_NOT_DIRECT,
    MODEL_ENDPOINTS_URL_TEMPLATE,
    OUTPUT_CAP_PARAMETERS,
    REQUIRED_ENDPOINT_PARAMETERS,
    OpenRouterCatalogError,
    OpenRouterEndpointSnapshot,
    OpenRouterExecutionEvidence,
    inspect_openrouter_execution,
    select_catalog_endpoint,
    select_output_cap_parameter,
)

__all__ = [
    "CHAT_COMPLETIONS_URL",
    "LIMITATION_COST_UNUSABLE",
    "LIMITATION_METADATA_MISSING",
    "LIMITATION_REQUESTED_MISMATCH",
    "LIMITATION_RESPONSE_MODEL_MISMATCH",
    "LIMITATION_ROUTER_RETRIED",
    "LIMITATION_SELECTED_MODEL_MISMATCH",
    "LIMITATION_SELECTED_NOT_UNIQUE",
    "LIMITATION_SELECTED_PROVIDER_MISMATCH",
    "LIMITATION_STRATEGY_NOT_DIRECT",
    "MODEL_ENDPOINTS_URL_TEMPLATE",
    "OUTPUT_CAP_PARAMETERS",
    "REQUIRED_ENDPOINT_PARAMETERS",
    "ChatTransport",
    "OpenRouterAdapter",
    "OpenRouterCatalogError",
    "OpenRouterConfig",
    "OpenRouterEndpointSnapshot",
    "OpenRouterExecutionEvidence",
    "ProviderFailure",
    "ProviderFailureKind",
    "ProviderOutcome",
    "ProviderRefusal",
    "ProviderText",
    "TransportResponse",
    "httpx_chat_transport",
    "inspect_openrouter_execution",
    "select_catalog_endpoint",
    "select_output_cap_parameter",
]
