"""Pure, immutable domain contracts for job analysis(§9、§10 凍結形狀)。"""

from .base import DomainModel, Identifier, NonEmptyText, TaskId
from .proposal import (
    ALLOWED_STATUS_TRANSITIONS,
    TERMINAL_STATUSES,
    JdEntry,
    JdTask,
    JdTaskFields,
    MergeTarget,
    Proposal,
    ProposalAction,
    ProposalStatus,
    ProposalTarget,
    ResponsibilityRole,
    RevisionRequestResolution,
    SingleTaskTarget,
    SplitTarget,
    StagedTask,
    StagedTaskLineage,
    StagedWorkModelDelta,
    is_allowed_transition,
    jd_map,
    validate_edited_jd_after,
)
from .sources import SourceAnchor, SourceKind, SourceRef, SupportLink
from .task import (
    Enabler,
    EnablerKind,
    Retirement,
    RetirementKind,
    RetirementReason,
    Task,
    TaskFields,
    TaskState,
)
from .work_model import (
    CurrentWorkModel,
    ExcludedSignal,
    ExclusionReason,
    OpenIssue,
    OpenIssueKind,
)

__all__ = [
    "ALLOWED_STATUS_TRANSITIONS",
    "CurrentWorkModel",
    "DomainModel",
    "Enabler",
    "EnablerKind",
    "ExcludedSignal",
    "ExclusionReason",
    "Identifier",
    "JdEntry",
    "JdTask",
    "JdTaskFields",
    "MergeTarget",
    "NonEmptyText",
    "OpenIssue",
    "OpenIssueKind",
    "Proposal",
    "ProposalAction",
    "ProposalStatus",
    "ProposalTarget",
    "Retirement",
    "RetirementKind",
    "RetirementReason",
    "ResponsibilityRole",
    "RevisionRequestResolution",
    "SingleTaskTarget",
    "SourceAnchor",
    "SourceKind",
    "SourceRef",
    "SplitTarget",
    "StagedTask",
    "StagedTaskLineage",
    "StagedWorkModelDelta",
    "SupportLink",
    "TERMINAL_STATUSES",
    "Task",
    "TaskFields",
    "TaskId",
    "TaskState",
    "is_allowed_transition",
    "jd_map",
    "validate_edited_jd_after",
]
