/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 職能基準(OCS)來源文件 — pdf-to-json 產出、ocs-indexer 消費的交換格式。
 */
export interface OCSDocument {
  version_info?: VersionInfo;
  ocs_profile: OcsProfile;
  ocs_content?: OcsContent;
  ocs_attitude?: OcsAttitude;
  notes?: Notes;
}
export interface VersionInfo {
  versions?: VersionEntry[];
}
export interface VersionEntry {
  version?: string;
  ocs_code?: string;
  ocs_name?: string;
  status?: string;
  update_note?: string | null;
  update_date?: string;
}
export interface OcsProfile {
  ocs_code: string;
  ocs_name?: OcsName;
  category?: Category;
  job_description?: string;
  ocs_level?: number | null;
}
export interface OcsName {
  job_category_name?: string | null;
  occupation_name?: string | null;
}
export interface Category {
  job_categories?: CodeName[];
  occupations?: CodeName[];
  industries?: CodeName[];
}
/**
 * OCS code↔name 條目;code/name 容忍缺漏(消費端 lockstep 過濾),但結構必為物件(防 string 飄移)。
 */
export interface CodeName {
  code?: string | null;
  name?: string | null;
}
export interface OcsContent {
  ocu_units?: OcuUnit[];
}
export interface OcuUnit {
  ocu_code?: string;
  ocu_name?: string;
  tasks?: TaskGroup[];
}
export interface TaskGroup {
  task_codes?: CodeName[];
  competency_blocks?: CompetencyBlock[];
  details?: TaskDetails | null;
}
export interface CompetencyBlock {
  competency_level?: number | null;
  indicators?: CodeText[];
  outputs?: CodeName[];
  knowledge?: CodeName[];
  skills?: CodeName[];
}
export interface CodeText {
  code?: string | null;
  text?: string | null;
}
/**
 * 任務客製細項(訪談引擎 v1,ADR 0023/spec 2026-07-05;OCS 官方來源沒有——由訪談產生,全部 optional。溯源(quote)不落文件,住訪談 session。
 */
export interface TaskDetails {
  frequency?: string | null;
  time_share_pct?: number | null;
  duration?: string | null;
  volume?: string | null;
  trigger?: string | null;
  inputs?: string | null;
  tools?: string | null;
  collaborators?: string | null;
  wait_points?: string | null;
  exceptions?: string | null;
  standards?: string | null;
}
export interface OcsAttitude {
  attitudes?: CodeName[];
}
export interface Notes {
  prerequisites?: string[];
  supplements?: string[];
}
